module.exports = [
    {
        id:1,
        name:"Gaurav",
        mail:"gaurav@meta.com",
        status:"active"
    },
    {
        id:2,
        name:"Hansu",
        mail:"hansu@meta.com",
        status:"active"
    },
    {
        id:3,
        name:"sam",
        mail:"sam@meta.com",
        status:"inactive"
    },
    {
        id:4,
        name:"suraj",
        mail:"suraj@meta.com",
        status:"active"
    },
    {
        id:5,
        name:"raj",
        mail:"raj@meta.com",
        status:"active"
    },
    {
        id:6,
        name:"jack",
        mail:"jack@meta.com",
        status:"inactive"
    },
    {
        id:7,
        name:"ram dev",
        mail:"ramDev@meta.com",
        status:"active"
    },
    {
        id:8,
        name:"hp",
        mail:"hp@google.com",
        status:"inactive"
    },
    {
        id:9,
        name:"acer",
        mail:"acer@google.com",
        status:"active"
    },
    {
        id:10,
        name:"lenovo",
        mail:"lenovo@meta.com",
        status:"inactive"
    }
]